### ISSUE TITLE
Create crawler benchmarking testbed

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/katana#3]
## Tasks 

- [x] Headless testbed
- [x] Non-headless testbed
- [x] Add crawl scoring
- [ ] Cover variety of scenarios like login / register / logout / dynamic links / event listeners / random ids, etc.

## Resources

- https://github.com/google/security-crawl-maze
- AJAX scenarios for crawler navigation testing
